version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8
    container_name: nawy-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nawy
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - nawy-network

  # Backend API
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: nawy-backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
      PORT: 5000
      # Updated for MySQL
      DATABASE_URL: mysql://user:password@mysql:3306/nawy
    depends_on:
      - mysql
    networks:
      - nawy-network

  # Frontend
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: nawy-frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: http://backend:5000
    depends_on:
      - backend
    networks:
      - nawy-network

networks:
  nawy-network:
    driver: bridge

volumes:
  postgres_data: